sudo: false
dist: trusty

language: c

compiler:
  - gcc
  - clang-3.8

branches:
  only:
    - master
    - clang-cfi

env:
  - RUNTIME=libicu
  - RUNTIME=libidn2
  - RUNTIME=libidn
  - RUNTIME=no

addons:
  apt:
    packages:
      - automake
      - autoconf
      - autopoint
      - libtool
      - gtk-doc-tools
      - gettext
      - libidn11-dev
      - libidn2-0-dev
      - libicu-dev
      - libunistring-dev
      - lcov
      - clang-3.8
      - llvm-3.8-dev
      - llvm-dev

script:
  - ./autogen.sh
#  CFI doesn't work out on Ubuntu 14.04 (Trusty). They dont't include LLVMgold.so for clang-3.8.
#  clang-3.4 doesn't know CFI yet.
#  The only chance with Travis-CI is to switch to docker and use Ubuntu 16.04 or whatever.
#  - if [[ $CC == "gcc" ]]; then CFI=""; else CFI="--enable-cfi"; fi
  - ./configure $CFI && make -j4 && make check -j4 || (cat config.log; ls -la /usr/lib/*gold*)
  - ./configure $CFI --enable-runtime=$RUNTIME --enable-builtin=libicu && make clean && make -j4 && make check -j4
  - ./configure $CFI --enable-runtime=$RUNTIME --enable-builtin=libidn2 && make clean && make -j4 && make check -j4
  - ./configure $CFI --enable-runtime=$RUNTIME --enable-builtin=libidn && make clean && make -j4 && make check -j4
  - ./configure $CFI --enable-runtime=$RUNTIME --disable-builtin && make clean && make -j4 && make check -j4
  - ./configure --enable-gtk-doc && make -j4 && make check -j4
  - make distcheck
  - if [[ $CC == "gcc" && $RUNTIME == "libicu" ]]; then ./.travis_coveralls.sh; fi
